### DISCUSSION TITLE
Easier management of repository activities

### DISCUSSION THREAD

**Discussion by sinisaos** [piccolo-orm/piccolo_admin#154] [Ideas]
Maybe we should consider using something like [this](https://github.com/marketplace/actions/pull-request-reviewee-reminder-action) or  [this](https://github.com/marketplace/actions/close-stale-issues) as a reminder to review PR or issues, because it doesn't make sense to do stale PRs without closing, merging or activities.

I think with these actions it would be easier to monitor repository activities and reduce stale issues and PRs.

**Comment by dantownsend** [comment]
Yeah, they are interesting - the reminder action might help.

The main problem is getting a larger pool of reviewers, and making it clear what the status of a PR is.

For example, I usually look at a PR as soon as it is opened, but I can't merge it in until I've cloned it locally, and tested it properly. The testing takes quite a long time.

Ideally there would be a checklist for each PR - something along the lines of:

 1. Does the code look good?
 2. Has it been tested locally, and works as expected?
 3. Does the PR contain documentation and tests?
 4. In the case of Piccolo Admin, is a screenshot of the new feature attached?

When a PR is opened, it enter's a `waiting for reviewer` step. Ideally then, one or more people assign themselves as reviewers. A checklist is also created, so it's clear to everyone the current status of the PR, and why it might be blocked.

I think this is one of the main challenges for levelling Piccolo up as a project. I'm sure things like this are possible in GitHub, but I don't know how.

Alongside these improvements to the PR process, using something like Discord might help to co-ordinate development better. But again, it's not something I've used much.

For Piccolo Admin in particular, I think additional tests would make reviewing easier. We have the Cypress tests, but I haven't figured out how to integrate them into our CI, so we know at a glance that a PR introduces no issues.

**Reply by sinisaos** [reply]
The process you described would be ideal, but I don’t know how we could do it. I think a reminder would be useful solely as a reminder that the things you described should be done. We should have this in all Piccolo repositories solely for the reason that some good PRs do not remain unused.

**Reply by dantownsend** [reply]
OK, let's add the reminder. Something like 5 days after a PR has been opened it could ask for a status update.

We can trial it in this repo.

If you can figure out solutions to any of those other things, that would be great. GitHub is a skillset in its own right!

**Reply by sinisaos** [reply]
That's great. So we'll see how that turns out.

**Reply by dantownsend** [reply]
Do you want to create the PR, or should I?

**Reply by sinisaos** [reply]
Can you please do that. Thanks.

**Comment by dantownsend** [comment]
This one looks the most feature rich - has a lot of options to work through though. https://github.com/marketplace/actions/close-stale-issues

**Reply by sinisaos** [reply]
I agree. I think this example from documentation would be ok.
```yaml
# in .github/workflows/stale.yml
name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '30 1 * * 5' # runs every 5 days

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v4
        with:
          stale-issue-message: 'This issue is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 5 days.'
          stale-pr-message: 'This PR is stale because it has been open 45 days with no activity. Remove stale label or comment or this will be closed in 10 days.'
          close-issue-message: 'This issue was closed because it has been stalled for 5 days with no activity.'
          close-pr-message: 'This PR was closed because it has been stalled for 10 days with no activity.'
          days-before-issue-stale: 30
          days-before-pr-stale: 45
          days-before-issue-close: 5
          days-before-pr-close: 10
```
Change the messages and expiration time (deletion) as you think is best.

**Reply by dantownsend** [reply]
Thanks - I've added it.

For now I've made it so it just prompts on PRs, as these are the most important.

**Comment by dantownsend** [comment]
I'm not sure if this is in anyway relevant, but GitHub recently released a new version of GitHub Issues:

https://github.blog/2021-06-23-introducing-new-github-issues/
https://github.com/features/issues

I haven't had time to investigate yet, but it might also help keep on top of things.

**Reply by sinisaos** [reply]
This new GitHub Issues looks nice but I think this stale action will be enough for us. Over time, we need to include issues because there are plenty of inactive ones.

Can you fix typo in scheduler?

```yaml
schedule:
    - cron: "30 1 */5 * *" # runs every 5 days
```

or even better yet every 3 days

```yaml
schedule:
    - cron: "30 1 */3 * *" # runs every 3 days
```

**Reply by dantownsend** [reply]
Thanks, good spot - I've changed it to run every 3 days.

**Comment by sinisaos** [comment]
@dantownsend The reminder works well. I think we should apply this action to issues either and also set the closing of PRs and issues to automate this process and make management easier. Something like this

```yaml
stale-pr-message: "This PR has been marked as stale because it has been open for 30 days with no activity. Are there any blockers, or should this be closed?"
stale-issue-message: 'This issue has been marked as stale because it has been open for 30 days with no activity. Are there any blockers, or should this be closed?'
close-pr-message: 'This PR was closed because it has been stalled with no activity.'
close-issue-message: 'This issue was closed because it has been stalled with no activity.'
days-before-pr-stale: 30
days-before-issue-stale: 30
days-before-pr-close: 5
days-before-issue-close: 5
```

If that also works well you should apply them to all Piccolo repos.
