### ISSUE TITLE
Automate running of Cypress tests

### ISSUE THREAD

**Issue by dantownsend** [piccolo-orm/piccolo_admin#85]
Now we have some basic Cypress tests, it is worth investigating how we can run these as part of GitHub actions.

Cypress tests can be notoriously slow, so we might not want to run them on every commit - we will have to see what the performance is like.

**Comment by LeMeteore** [comment]
What about something like:
```
on:
    release:
        types:
            - created

jobs:
    cypress-tests:
        name: "Run Cyress tests"
        runs-on: "ubuntu-latest"
        steps:
              run:   # command to run cypress
```

Or something like:
```
on: [push]
jobs:
  cypress-tests:
    name: "Run Cyress tests"
    if: github.actor == 'foobar'
    runs-on: ubuntu-latest
    steps:
      - run: # command to run cypress tests
```

[Doc](https://docs.github.com/en/actions/using-jobs/using-conditions-to-control-job-execution)
